accounts:
  - address: "0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef" # Required
    abi_path: "build/EventLinkedStorage.abi" # Required in event mode
    head_slot: "0x0" # Required in event mode
    count_slot: "0x1" # Required in sparse mode for contract monitoring
